name: marquee
description: "A Flutter widget that scrolls text infinitely. Provides many
  customizations including custom scroll directions, durations, curves as well
  as pauses after every round."
version: 2.3.0
homepage: https://github.com/MarcelGarus/marquee
repository: https://github.com/MarcelGarus/marquee
issue_tracker: https://github.com/MarcelGarus/marquee/issues

environment:
  flutter: ">=3.12.0"
  sdk: "^3.5.0"

dependencies:
  fading_edge_scrollview: ^4.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
